config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "listings#index"
  get "listings/my_listings", to: "listings#my_listings", as: :my_listings
  get "bookings/my_booking_requests", to: "bookings#my_booking_requests", as: :my_booking_requests
  resources :listings do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:index, :show, :edit, :update] do
    member do
      patch :accept
      patch :refuse
    end
  end

  get "about_me" => "users#show", as: "about_me"
  get "about_me/edit" => "users#edit", as: "edit_about_me"
  patch "about_me" => "users#update"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :listing

  private

  def calculate_total_price
    if date_start && date_end && listing && listing.price_per_day
      duration_in_days = (date_end - date_start).to_i + 1
      duration_in_days = [duration_in_days, 1].max
      self.total_price = duration_in_days * listing.price_per_day
    else
      self.total_price = nil
    end
  end
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  has_many :bookings, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :bookings
  has_many :listings
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  geocoded_by :city
  after_validation :geocode, if: :will_save_change_to_city?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name bio city])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name bio city])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  #new booking must be created in association of a listing
  before_action :set_listing, only: [:new, :create]

  def index
    #only the users who are loged in
    @bookings = Booking.where(user_id: current_user.id)
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = @listing.bookings.new(booking_params)
    @booking.user = current_user # user_id

    if @booking.date_start && @booking.date_end
      days = (@booking.date_end - @booking.date_start).to_i + 1
      @booking.total_price = days * @listing.price_per_day
    end

    if @booking.save
      flash[:notice] = "Booking for #{@listing.album_name} was successfully created!"
      redirect_to bookings_path
    else
      flash.now[:alert] = "Could not create booking: #{@booking.errors.full_messages.to_sentence}"
      render 'listings/show', status: :unprocessable_entity
    end
  end

  def my_booking_requests
    @user = current_user
    @bookings = Booking.where(user_id: current_user)
    @listings = Listing.where(user_id: current_user)
  end

  def accept
    @booking = Booking.find(params[:id])
    @booking.update(accepted: true)
    redirect_to my_booking_requests_path, notice: "Booking accepted."
  end

  def refuse
    @booking = Booking.find(params[:id])
    @booking.update(accepted: false)
    redirect_to my_booking_requests_path, notice: "Booking accepted."
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def edit
  end

  def update
    if @booking.update(booking_params)
      redirect_to booking_path(@booking), notice: "Your booking is updated!"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_listing
    @listing = Listing.find(params[:listing_id])
  end

  def booking_params
    params.require(:booking).permit(:date_start, :date_end, :status, :total_price)
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

  def index
    @listings = Listing.all
    if params[:query].present?
      sql_subquery = "album_name ILIKE :query OR artist_name ILIKE :query OR genre ILIKE :query"
      @listings = @listings.where(sql_subquery, query: "%#{params[:query]}%")
    end

    @markers = @listings.map do |listing|
      user = listing.user
      if user.latitude.present? && user.longitude.present?
        {
          lat: user.latitude,
          lng: user.longitude,
          info_window_html: render_to_string(partial: "info_window", locals: { listing: listing }),
          marker_html: render_to_string(partial: "marker", locals: { listing: listing })
        }
      end
    end
  end

  def new
   @listing = Listing.new
  end

  def create
    @listing = Listing.new(listing_params)
    @listing.user = current_user
    if @listing.save
      redirect_to listing_path(@listing)
    else
    render :new, status: :unprocessable_entity
    end
  end

  def my_listings
    @listings = Listing.where(user_id: current_user.id)
  end

  def show
    @listing = Listing.find(params[:id])
    @booking = Booking.new
  end

  def edit
    @listing = Listing.find(params[:id])
  end

  def update
    @listing = Listing.find(params[:id])
    if @listing.update(listing_params)
      redirect_to listing_path(@listing)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @listing = Listing.find(params[:id])
    @listing.destroy
    redirect_to listings_path, status: :see_other
  end

  private

  def listing_params
    params.require(:listing).permit(:album_name,:artist_name, :tracklist, :description, :genre, :youtube_url, :price_per_day, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = current_user
    @listings = @user.listings
  end

  def my_listings
    @listings = current_user.listings
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to about_me_path, notice: "Bio updated!"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:bio)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<%= simple_form_for [@listing, @booking],
  url: listing_bookings_path(@listing),
  html: {
    data: {
      controller: "booking",
      "booking-price-per-day-value": @listing.price_per_day
    }
  } do |f| %>

  <%= f.input :date_start, as: :string, input_html: {
      data: {
        controller: "datepicker",
        booking_target: "dateStart",
        datepicker_target: "input"
      }
    } %>

  <%= f.input :date_end, as: :string, input_html: {
      data: {
        controller: "datepicker",
        booking_target: "dateEnd",
        datepicker_target: "input"
      }
    } %>
  <div class="total-price-badge">Total price:
  <span data-booking-target="totalPrice">0€</span>
</div>
<div class="submit-button-wrapper">
  <%= f.button :submit, "Submit Request", class: "btn btn-outline-light" %>
</div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Bookings#edit</h1>
<p>Find me in app/views/bookings/edit.html.erb</p>

app/views/bookings/index.html.erb
<div class="container-fluid full-height">
  <div class="row justify-content-center">
    <div class="col-10 ms-5 my-3">
      <h1> My Bookings: </h1>
      <% if @bookings.any? %>
        <div class="card-container">
          <% @bookings.each do |booking| %>
            <div class="card-product">
              <%= link_to listing_path(booking.listing), class: "card-product-link" do %>
                <% if booking.listing.photo.attached? %>
                  <%= cl_image_tag booking.listing.photo.key %>
                <% end %>

                <div class="card-product-infos">
                  <h2><%= booking.listing.album_name %></h2>
                  <p><strong>Start Date: </strong><%= booking.date_start.present? ? booking.date_start.strftime("%b %d, %Y") : "Not set" %></p>
                  <p><strong>End Date: </strong><%= booking.date_end.present? ? booking.date_end.strftime("%b %d, %Y") : "Not set" %></p>
                  <p><strong>Total Price:</strong> <%= number_to_currency(booking.total_price, unit: "€") %></p>

                  <% if booking.accepted == true %>
                    <% booking.status = "accepted" %>
                  <% elsif booking.accepted == false %>
                    <% booking.status = "refused" %>
                  <% else %>
                    <% booking.status = "pending" %>
                  <% end %>

                  <p><strong>Status:</strong>
                    <% if booking.status == "accepted" %>
                      <span class="accepted"><%= booking.status %></span>
                    <% elsif booking.status == "refused" %>
                      <span class="refused"><%= booking.status %></span>
                    <% else %>
                      <span class="pending"><%= booking.status %></span>
                    <% end %>
                  </p>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/bookings/my_booking_requests.html.erb
<div class="container-fluid full-height">
  <div class="row d-flex justify-content-center">
    <div class="col-8 justify-content-start">
      <h1>My Booking Requests</h1>
      <div class="card-container">
      <% @listings.each do |listing| %>
        <% listing.bookings.each do |booking| %>
            <div class="card-product">
              <% if booking.listing.photo.attached? %>
              <%= cl_image_tag booking.listing.photo.key %>
              <% end %>
              <div class="card-product-infos">
              <% if booking.accepted.nil? %>
                <p><%= booking.user.first_name %> requested to book <%= booking.listing.album_name %> from <%= booking.date_start %> to <%= booking.date_end %></p>
                <p class="mb-3">Your payout would be: <%= booking.total_price %>€</p>
                  <%= link_to "Accept the Booking", accept_booking_path(booking), data: { turbo_method: :patch, turbo_confirm: "Are you sure?" }, class: "btn btn-primary ms-3" %>
                  <%= link_to "Refuse the Booking", refuse_booking_path(booking), data: { turbo_method: :patch, turbo_confirm: "Are you sure?"}, class: "btn btn-danger ms-3 mt-3" %>
              </div>
              <% else %>
                <p><%= booking.user.first_name %> requested to book <%= booking.listing.album_name %></p>
                <p>They requested to book it from <%= booking.date_start %> to <%= booking.date_end %></p>
                <p>Your payout: <%= booking.total_price %>€</p>
                <p>Booking Status: <%= booking.accepted ? "Accepted" : "Refused" %></p>
              </div>
              <% end %>
              </div>
        <% end %>
      <% end %>
</div>
</div>

app/views/bookings/show.html.erb
<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-6">
      <div class = "p-4">
        <h2>Just a few days before you can enjoy listening to <%= @booking.listing.artist_name %></h2>

        <div class="card-product ">
          <% if @booking.listing.photo.attached? %>
            <%= cl_image_tag @booking.listing.photo.key %>
          <%end%>
        </div>

        <div class="card-product-infos mt-4">
          <h2><%= @booking.listing.album_name %></h2>
          <p>Start date <%= @booking.date_start%></p>
          <p>End date <%= @booking.date_end%></p>
          <p><%= @booking.status%>
        </div>

        <% if user_signed_in? %>
        <%= link_to "Back to my bookings", bookings_path %>
        <%= link_to "Find new vinyls", listings_path %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/bookings/update.html.erb
<h1>Bookings#update</h1>
<p>Find me in app/views/bookings/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VinylBnb</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css", media: "all" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= render "shared/flashes" %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/listings/_form.html.erb
  <%= simple_form_for (@listing) do |f| %>
    <%= f.input :album_name %>
    <%= f.input :artist_name %>
    <%= f.input :tracklist %>
    <%= f.input :description %>
    <%= f.input :genre %>
    <%= f.input :youtube_url %>
    <%= f.input :price_per_day %>
      <% unless @listing.new_record? %>
        <%= f.input :active %>
      <% end %>
    <%= f.input :photo, as: :file %>

    <%= f.button :submit %>
  <% end %>

app/views/listings/_info_window.html.erb
<div class="custom-popup-content">
  <div class="card">
    <div class="one">
      <span class="title"><%= listing.album_name %></span>
      <%= link_to listing_path(listing), class: "music-link" do %>
        <div class="music" style="background-image: url(<%= cl_image_path(listing.photo.key) %>)"></div>
      <% end %>
  </div>
  <div class="two"></div>
  <div class="three"></div>
</div>
</div>

app/views/listings/_marker.html.erb
<%= image_tag "https://storage.googleapis.com/qover-assets/Logos/logo-bnb.png", height: 30, width: 30, alt: "Logo" %>

app/views/listings/edit.html.erb
<div>
  <h1>Edit my listing</h1>
  <%= render "form", listing: @listing %>
</div>

app/views/listings/index.html.erb
<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-sm-4 my-3">
      <%= form_with url: listings_path, method: :get, class: "search-form d-flex my-5" do %>
        <%= text_field_tag :query,
              params[:query],
              class: "form-control",
              placeholder: "Search by album, artist or genre" %>
        <%= submit_tag "Search", name: "", class: "btn btn-primary search-button" %>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-8 justify-content-center">
      <h1 class="ms-4">List of all vinyls</h1>
      <div class="card-container">
        <% @listings.each do |listing| %>
          <% if listing.active? %>
            <div class="card-product">
            <%= link_to listing_path(listing), class: "card-product-link" do %>
              <% if listing.photo.attached? %>
              <%= cl_image_tag listing.photo.key %>
              <% end %>
              <div class="card-product-infos">
                <h2><%= listing.album_name %></h2>
                <p><i class="fa-solid fa-podcast"></i>  <%= listing.artist_name %></p>
                <p><i class="fa-solid fa-tag"></i> <%= listing.genre %></p>
                <p><%= listing.price_per_day %> € / per day</p>
                <%= link_to "See vinyls details", listing_path(listing), class:"button"%>
              </div>
            </div>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>

    <div class="col-4 pe-4 rounded">
      <h1 class="mb-5">Map view</h1>
      <div class="map sticky-top"
        data-controller="map"
        data-map-markers-value="<%= @markers.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>
</div>

app/views/listings/my_listings.html.erb
<div class="container-fluid full-height">
  <div class="row d-flex justify-content-center">
    <div class="col-8 justify-content-start">
      <h1>My listings</h1>
      <div class="card-container">
        <% @listings.each do |listing| %>
        <div class="card-product">
          <% if listing.photo.attached? %>
          <%= cl_image_tag listing.photo.key %>
          <% end %>
          <div class="card-product-infos">
            <h2><%= listing.album_name %></h2>
            <p>Artist: <%= listing.artist_name %></p>
            <p>Genre: <%= listing.genre %></p>
            <p>Price/day <%= listing.price_per_day %>0€</p>
            <% if listing.active == true %>
              <p>Listing is activated</p>
            <% else %>
              <p>Listing is deactivated</p>
            <% end %>
            <%= link_to "See vinyls details", listing_path(listing), class: "card-button" %>
          </div>
        </div>
        <% end %>
        </div>
      </ul>

    </div>
  </div>
</div>

app/views/listings/new.html.erb
<div class="form-container">
  <h1>Create a new listing</h1>
  <%= render "form" %>
</div>

app/views/listings/show.html.erb
<div class="playlist-banner">
  <div class="playlist-cover">
    <img src="<%= cl_image_path(@listing.photo.key) %>" alt="Album Cover">
  </div>
  <div class="playlist-details">
    <h1 class="playlist-title">
      <span class="artist"><%= @listing.artist_name %></span> – <%= @listing.album_name %>
    </h1>
    <div class="playlist-meta d-flex flex-column align-items-start mt-2">
      <span class="meta-info">Rented by: <%= @listing.user.first_name %></span>
      <span class="meta-info">Description: <%= @listing.description %></span>
      <span class="meta-info">Price per day: <%= @listing.price_per_day %></span>
    </div>
  </div>
</div>

  <div class="container-fluid">
    <div class="row justify-content-center">
      <div class="col-sm-10 col-lg-7 mt-5">
        <p>Artist:
        <%= link_to @listing.artist_name, listings_path(query: @listing.artist_name) %> </p>
        <p>Tracklist: <%= @listing.tracklist %></p>
        <h3>Artist: <%= @listing.artist_name %></h3>
        <strong>Tracklist</strong>
        <ul class= "tracklist">
          <% @listing.tracklist.split("\n").each do |track| %>
            <li><%= track %></li>
          <% end %>
        </ul>
        <p>Description: <%= @listing.description %></p>
        <p>Genre:
        <%= link_to @listing.genre, listings_path(query: @listing.genre) %> </p>
        <p><%= link_to "Preview on Youtube", @listing.youtube_url, target: "_blank" %></p>
        <p>Price per day: <%= @listing.price_per_day %>€</p>
        <% if user_signed_in? && current_user.id == @listing.user_id %>
          <p>Listing active: <%= @listing.active %></p>
        <% end %>
        <p>User:
        <%= link_to @listing.user.first_name, listings_path(query: @listing.user.first_name) %> </p>

        <%= link_to "Back to all listings", listings_path %>
        <% if user_signed_in? && current_user.id == @listing.user_id %>
          <%= link_to "Edit my listing", edit_listing_path(@listing) %>
          <%= link_to "Delete this record", listing_path(@listing), data: {turbo_method: :delete, turbo_confirm: "Do you REALLY want to delete?"} %>
        <% end %>

        <% if user_signed_in? %>
          <%= link_to "Book this vinyl", new_listing_booking_path(@listing) %>
        <% end %>
      </div>
      <div class="col-sm-10 col-lg-3 mt-5">
        <h2 class="mb-5">Book this vinyl</h2>
        <%= render "bookings/form" %></div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="custom-flash notice alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="custom-flash alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer text-center py-3 mt-auto">
  <p class="mb-0 text-muted small">
    Made with ❤️ from students of Le Wagon.<br>
    Pelin, Marta, Sneha, Sam and Matthieu
  </p>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-dark navbar-lewagon">
  <div class="container-fluid">
    <%= link_to listings_path, class: "navbar-brand ms-4" do %>
      <%= image_tag "logo.png", class: "navbar-brand" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Create a new vinyl listing", new_listing_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "All Listings", listings_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <div class="hamburger d-flex justify-content-center">
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" aria-hidden="true" role="presentation" focusable="false" style="display: block; fill: none; height: 20px; width: 20px; stroke: currentcolor; stroke-width: 3; overflow: visible; margin: auto"><g fill="none"><path d="M2 16h28M2 24h28M2 8h28"></path></g></svg>
            </div>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "About me", about_me_path, class: "dropdown-item" %>
              <%= link_to "My bookings", bookings_path, class: "dropdown-item" %>
              <%= link_to "My listings", my_listings_path, class: "dropdown-item" %>
              <%= link_to "My booking requests", my_booking_requests_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Edit Bio</h1>

<%= simple_form_for @user, url: about_me_path, method: :patch do |f| %>
  <%= f.input :bio, as: :text, label: "Your bio", input_html: { rows: 2 } %>
  <%= f.submit "Update Bio", class: "btn btn-primary search-button" %>
<% end %>

app/views/users/show.html.erb
<div class="container-fluid full-height">
<div class="row justify-content-center">
    <div class="col-10 ms-5 my-3">
    <h1 class="mb-5">About me</h1>
      <p><strong>First name:</strong> <%= @user.first_name %></p>
      <p><strong>Last name:</strong> <%= @user.last_name %></p>
      <p><strong>Location:</strong> <%= @user.city %></p>
      <p class="mb-4"><strong>Bio:</strong> <%= @user.bio.presence || "No bio added yet." %></p>

      <% if @user.bio.blank? %>
        <%= link_to "Add bio", edit_about_me_path, class: "button" %>
      <% else %>
        <%= link_to "Edit bio", edit_about_me_path, class: "button" %>
      <% end %>

  </div>
  </div>

<!--<div style="width: 40%; height: 600px;"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>-->
<div class="row justify-content-center">
  <div class="col-10 ">
  <h1 class="mt-5 mb-4 ms-4">List of my vinyls</h1>

  <% if @listings.any? { |listing| listing.active? } %>
    <div class="card-container">
        <% @listings.each do |listing| %>
          <% if listing.active? %>
            <div class="card-product">
              <% if listing.photo.attached? %>
              <%= cl_image_tag listing.photo.key %>
              <% end %>
              <div class="card-product-infos">
            <h2><%= listing.album_name %></h2>
            <p><i class="fa-solid fa-podcast"></i>  <%= listing.artist_name %></p>
            <p><i class="fa-solid fa-tag"></i> <%= listing.genre %></p>
            <p class="mb-4"><%= listing.price_per_day %> € / per day</p>
            <%= link_to "See vinyls details", listing_path(listing), class:"button"%>
          </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  <% else %>
    <p>You have no active vinyl listings.</p>
  <% end %>
</div>
</div>
</div>